name: Build libplacebo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: [ windows-latest ]
    #          - os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: haasn/libplacebo
          path: libplacebo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Meson
        run: pip install meson ninja jinja2

      - name: Configure static build
        shell: bash
        working-directory: ./libplacebo
        run: |
          meson setup build \
          --buildtype=release \
          --default-library=static \
          --prefix=/tmp/libplacebo-static \
          -Dshaderc=disabled \
          -Dvulkan=disabled \
          -Dlcms=disabled \
          -Ddovi=disabled \
          -Dglslang=disabled \
          -Dopengl=disabled \
          -Dd3d11=disabled

      - name: Compile and install
        shell: bash
        working-directory: ./libplacebo
        run: |
          meson compile -C build
          meson install -C build

      - name: Package library
        shell: bash
        run: |
          cd /tmp/libplacebo-static
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            7z a libplacebo-static-${{ runner.os }}.zip ./*
          else
            tar czvf libplacebo-static-${{ runner.os }}.tar.gz ./*
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libplacebo-static-${{ runner.os }}
          path: /tmp/libplacebo-static/libplacebo-static-${{ runner.os }}.*