name: Build libplacebo

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            meson \
            ninja-build \
            git \
            python3 \
            python3-pip \
            libshaderc-dev \
            libvulkan-dev \
            liblcms2-dev \
            libdovi-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install meson ninja shaderc vulkan-headers lcms2 libdovi
          pip3 install --user meson

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y meson ninja python
          pip install meson
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe" -OutFile "vulkan-sdk.exe"
          Start-Process -Wait -FilePath "vulkan-sdk.exe" -ArgumentList "/S"

      - name: Configure and build
        run: |
          mkdir build
          cd build
          meson setup \
            --buildtype=release \
            --default-library=static \
            --prefix=/tmp/libplacebo \
            -Dshaderc=enabled \
            -Dvulkan=enabled \
            -Dlcms=enabled \
            -Ddovi=enabled \
            -Dglslang=disabled \
            -Dd3d11=disabled \
            -Dopengl=disabled \
            ..
          ninja
          ninja install

      - name: Package artifacts
        run: |
          cd /tmp/libplacebo
          if [ "$RUNNER_OS" = "Windows" ]; then
            7z a libplacebo-${{ runner.os }}.zip ./*
          else
            tar czvf libplacebo-${{ runner.os }}.tar.gz ./*
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libplacebo-${{ runner.os }}
          path: /tmp/libplacebo/libplacebo-${{ runner.os }}.*