name: Build dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ x86, x64 ]
    env:
      FFMPEG_VERSION: "7.1.1"
      PORTAUDIO_VERSION: "pa_stable_v190700_20210406"
      BUILD_DIR: ${{ github.workspace }}\build
      BIN_FOLDER: ${{ github.workspace }}\bin

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Install dependencies
        run: choco install -y cmake ninja yasm git

      - name: Create dirs
        run: |
          mkdir bin
          mkdir bin\ffmpeg
          mkdir bin\portaudio
          mkdir bin\klarity
          mkdir include
          mkdir include\ffmpeg
          mkdir include\portaudio

      - name: Build FFmpeg
        run: |
          git clone --depth=1 --branch=n${{ env.FFMPEG_VERSION }} https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          ./configure --toolchain=msvc --arch=${{ matrix.arch }} --target-os=win32 --enable-shared --disable-static --prefix="${{ env.BIN_FOLDER }}\ffmpeg"
          make -j
          make install
        shell: bash

      - name: Build PortAudio
        run: |
          git clone --depth=1 --branch=${{ env.PORTAUDIO_VERSION }} https://github.com/PortAudio/portaudio.git
          cd portaudio
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ env.BIN_FOLDER }}\portaudio"
          cmake --build . --target install
        shell: bash

      - name: Build Klarity
        run: |
          mkdir ${{ env.BUILD_DIR }}
          cd ${{ env.BUILD_DIR }}
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ env.BIN_FOLDER }}\klarity" -DBIN_FOLDER="${{ env.BIN_FOLDER }}"
          cmake --build . --target klarity
        shell: bash

      - name: Copy FFmpeg headers
        run: xcopy /E /I /Y ffmpeg /include ${{ env.BIN_FOLDER }}\..\include\ffmpeg

      - name: Copy PortAudio headers
        run: xcopy /E /I /Y portaudio\include ${{ env.BIN_FOLDER }}\..\include\portaudio

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: klarity-windows-${{ matrix.arch }}
          path: |
            bin
            include
