name: Build Windows dependencies

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  build_klarity_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Chocolatey Dependencies
        shell: pwsh
        run: |
          choco install nasm yasm cmake pkgconfiglite -y

      - name: Clone FFmpeg
        shell: pwsh
        run: git clone --branch n7.1 --depth 1 https://github.com/FFmpeg/FFmpeg.git

      - name: Build FFmpeg 7.1
        shell: cmd
        run: |
          cd FFmpeg
          ./configure --toolchain=msvc --arch=x86_64 --enable-shared --disable-static --enable-cuda --enable-nvenc --enable-cuvid --enable-d3d11va --enable-d3d12va --enable-libmfx --prefix=%GITHUB_WORKSPACE%\deps
          make -j%NUMBER_OF_PROCESSORS%
          make install

      - name: Clone PortAudio
        shell: pwsh
        run: git clone --branch v19.7.0 --depth 1 https://github.com/PortAudio/portaudio.git

      - name: Build PortAudio v19.7.0
        shell: cmd
        run: |
          cd portaudio
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX=%GITHUB_WORKSPACE%\deps
          cmake --build build --config Release --target install

      - name: Organize Required Files
        shell: pwsh
        run: |
          $depsPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "deps"
          if (!(Test-Path "$depsPath")) {
            New-Item -ItemType Directory -Path "$depsPath" -Force
          }

          if (!(Test-Path "$depsPath\\bin")) {
            New-Item -ItemType Directory -Path "$depsPath\\bin" -Force
          }

          $ffmpegBinPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "FFmpeg"
          Copy-Item -Path "$ffmpegBinPath\\*.dll" -Destination "$depsPath\\bin\\" -Force

          $portaudioBuildPath = Join-Path -Path $env:GITHUB_WORKSPACE -ChildPath "portaudio\\build\\Release"
          Copy-Item -Path "$portaudioBuildPath\\portaudio.dll" -Destination "$depsPath\\bin\\" -Force

      - name: Upload FFmpeg & PortAudio
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-portaudio-windows
          path: deps/

      - name: Build Klarity Library (Windows)
        shell: cmd
        run: |
          cd core/src/main/cpp
          cmake -DBIN_FOLDER=%GITHUB_WORKSPACE%\deps\bin -B build -G "Visual Studio 17 2022" -A x64
          cmake --build build --config Release

      - name: Upload Klarity Library
        uses: actions/upload-artifact@v4
        with:
          name: klarity-windows
          path: core/src/main/cpp/build/Release/