name: Build dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            binary_ext: so

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ unzip curl tar pkg-config nasm

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
        working-directory: ${{ runner.temp }}

      - name: Install vcpkg packages
        run: |
          ${{ runner.temp }}/vcpkg/vcpkg install --triplet ${{ matrix.triplet }}
        working-directory: ${{ github.workspace }}/core/src/main/cpp
        env:
          VCPKG_ROOT: ${{ runner.temp }}/vcpkg


      - name: Configure project
        run: |
          cmake -B build -S core/src/main/cpp -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ runner.temp }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build project
        run: cmake --build build --config Release --parallel

      - name: Copy binaries
        run: |
          mkdir -p output/bin
          cp -r build/* output/bin/
          cp ${{ github.workspace }}/core/src/main/cpp/vcpkg_installed/${{ matrix.triplet }}/lib/*${{ matrix.binary_ext }}* core/src/main/resources/bin/
          cp -r ${{ github.workspace }}/build/${{ matrix.os }}/*klarity*${{ matrix.binary_ext }}* core/src/main/resources/bin/

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build JARs
        run: |
          ./gradlew :core:shadowJar
          ./gradlew :compose:shadowJar
          ./gradlew :example:shadowJar

      - name: Clean up resources
        run: |
          rm -rf core/src/main/resources/bin

      - name: Copy JARs
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          cp core/build/libs/*.jar artifacts/${{ matrix.os }}/
          cp compose/build/libs/*.jar artifacts/${{ matrix.os }}/
          cp example/build/libs/*.jar artifacts/${{ matrix.os }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klarity-${{ matrix.os }}
          path: artifacts/${{ matrix.os }}