name: Build dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            binary_ext: .so

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up nasm
        uses: ilammy/setup-nasm@v1.5.2

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'core/src/main/cpp/vcpkg.debug.json'
          runVcpkgInstall: 'true'

        #      - name: Set up CMake
        #        uses: lukka/get-cmake@latest

      - name: Copy
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          cp ${{ github.workspace }}/installed/${{ matrix.triplet }}/lib/*${{ matrix.binary_ext }} artifacts/${{ matrix.os }}/lib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: artifacts/${{ matrix.os }}