name: Build dependencies

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            triplet: x64-windows
            binary_ext: dll

          - os: macos-latest-arm64
            triplet: arm64-osx
            binary_ext: dylib

          - os: macos-latest
            triplet: x64-osx
            binary_ext: dylib

          - os: ubuntu-latest-arm64
            triplet: arm64-linux
            binary_ext: so

          - os: ubuntu-latest
            triplet: x64-linux
            binary_ext: so

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up nasm
        if: matrix.os != 'windows-latest'
        uses: ilammy/setup-nasm@v1

      - name: Set up vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            ./vcpkg/bootstrap-vcpkg.bat
          else
            ./vcpkg/bootstrap-vcpkg.sh
          fi

      - name: Install dependencies
        run: |
          ./vcpkg/vcpkg install --x-manifest-root=${{ github.workspace }}/core/src/main/cpp 

      - name: Upload dependencies
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-dependencies
          path: ${{ github.workspace }}/core/src/main/cpp/vcpkg_installed/${{ matrix.triplet }}