name: Build dependencies

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            triplet: x64-windows-static

          - os: macos-latest-arm64
            triplet: arm64-osx

          - os: macos-13
            triplet: x64-osx

          - os: ubuntu-latest-arm64
            triplet: arm64-linux

          - os: ubuntu-latest
            triplet: x64-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up nasm
        if: matrix.os != 'windows-latest'
        uses: ilammy/setup-nasm@v1

      - name: Set up vcpkg
        shell: bash
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies
        shell: bash
        run: |
          ./vcpkg/vcpkg install \
          --x-manifest-root=${{ github.workspace }}/library/src/main/cpp \
          --x-install-root=${{ github.workspace }}/library/src/main/cpp/vcpkg_installed

      - name: Upload dependencies
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-dependencies
          path: ${{ github.workspace }}/library/src/main/cpp/vcpkg_installed/${{ matrix.triplet }}/