name: Build macOS dependencies

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  build_klarity_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        run: |
          brew install nasm yasm cmake autoconf automake libtool pkg-config

      - name: Build FFmpeg 7.1
        run: |
          git clone --branch n7.1 --depth 1 https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          ./configure --enable-shared --disable-static --disable-autodetect \
                      --enable-nvdec --enable-videotoolbox --enable-libmfx \
                      --extra-cflags=-I/usr/local/include \
                      --extra-ldflags=-L/usr/local/lib \
                      --prefix=$GITHUB_WORKSPACE/deps
          make -j$(sysctl -n hw.logicalcpu)
          make install

      - name: Build PortAudio v19.7.0
        run: |
          git clone --branch v19.7.0 --depth 1 https://github.com/PortAudio/portaudio.git
          cd portaudio
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/deps
          cmake --build build --config Release --target install

      - name: Organize Required Files
        run: |
          mkdir -p $GITHUB_WORKSPACE/deps/bin
          cp -a $GITHUB_WORKSPACE/deps/lib/*.dylib $GITHUB_WORKSPACE/deps/bin/
          cp -a $GITHUB_WORKSPACE/deps/lib/libportaudio.dylib $GITHUB_WORKSPACE/deps/bin/

      - name: Upload FFmpeg & PortAudio
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-portaudio-macos
          path: deps/

      - name: Build Klarity Library (macOS)
        run: |
          cd core/src/main/cpp
          cmake -DBIN_FOLDER=$GITHUB_WORKSPACE/deps/bin -B build -S .
          cmake --build build --config Release

      - name: Upload Klarity Library
        uses: actions/upload-artifact@v4
        with:
          name: klarity-macos
          path: core/src/main/cpp/build/
