name: Build JARs

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            triplet: x64-windows-static
            suffix: x64-win
          - os: macos-13
            triplet: x64-osx
            suffix: x64-osx
          - os: ubuntu-latest
            triplet: x64-linux
            suffix: x64-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: ${{ matrix.triplet }}

      - name: Create resources folder
        run: mkdir -p library/src/main/resources/bin

      - name: Copy binaries (Windows)
        if: matrix.os == 'windows-latest'
        run: cp klarity.dll library/src/main/resources/bin/

      - name: Copy binaries (macOS)
        if: matrix.os == 'macos-13'
        run: cp libklarity.dylib library/src/main/resources/bin/

      - name: Copy binaries (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cp libklarity.so library/src/main/resources/bin/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17.0.15+6

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Make binaries executable
        run: chmod +x library/src/main/resources/bin/* || true

      - name: Make JARs
        run: ./gradlew :library:jar -x test --no-daemon

      - name: Clean up resources
        run: |
          rm -rf library/src/main/resources/bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.triplet }}
          path: ${{ github.workspace }}/library/build/libs/klarity-1.0.0.jar