name: Build dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            binary_ext: so
    env:
      VCPKG_LIBRARY_LINKAGE: dynamic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ unzip curl tar pkg-config nasm

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: 'false'
          vcpkgJsonGlob: '**/core/src/main/cpp/vcpkg.json'

      - name: Configure project
        run: |
          cmake -B build -S core/src/main/cpp \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }}
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON

      - name: Build project
        run: cmake --build build --config Release --parallel

      - name: Copy binaries
        run: |
          mkdir -p output/bin
          cp -r build/* output/bin/
          cp ${{ github.workspace }}/build/vcpkg_installed/${{ matrix.triplet }}/bin/*${{ matrix.binary_ext }}* core/src/main/resources/bin/
          cp -r build/*klarity*${{ matrix.binary_ext }}* core/src/main/resources/bin/

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build JARs
        run: |
          ./gradlew :core:shadowJar
          ./gradlew :compose:shadowJar
          ./gradlew :example:shadowJar

      - name: Clean up resources
        run: |
          rm -rf core/src/main/resources/bin

      - name: Copy JARs
        run: |
          mkdir -p artifacts/${{ matrix.os }}
          cp core/build/libs/*.jar artifacts/${{ matrix.os }}/
          cp compose/build/libs/*.jar artifacts/${{ matrix.os }}/
          cp example/build/libs/*.jar artifacts/${{ matrix.os }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: klarity-${{ matrix.os }}
          path: artifacts/${{ matrix.os }}