name: Build dependencies

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            triplet: x64-linux
            artifact_name: linux-x64
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up nasm
        uses: ilammy/setup-nasm@v1.5.2

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'core/src/main/cpp/vcpkg.debug.json'
          runVcpkgInstall: 'true'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ env.VCPKG_ROOT }}/installed/${{ matrix.triplet }}