name: Build FFmpeg with CUDA support

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'

      - name: Install CUDA
        run: |
          choco install cuda --version=11.2  # Ensure CUDA is installed (version 11.2 or as needed)

      - name: Download FFmpeg source
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          git checkout release/5.1 # You can adjust the release version as necessary

      - name: Configure FFmpeg with CUDA support
        run: |
          cd ffmpeg
          ./configure --enable-nvenc --enable-nvdec --enable-cuda --enable-libnpp --enable-shared --prefix=%cd%/ffmpeg_build --extra-cflags="-I%cd%/ffmpeg_build/include" --extra-ldflags="-L%cd%/ffmpeg_build/lib"

      - name: Build FFmpeg with Visual Studio
        run: |
          cd ffmpeg
          msbuild /p:Configuration=Release /p:Platform=x64

      - name: Upload FFmpeg artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-build-artifacts
          path: |
            ffmpeg_build/include
            ffmpeg_build/bin
            ffmpeg_build/lib
