name: Build FFmpeg with CUDA Acceleration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
#        os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CUDA for Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install cuda --version=11.6
          setx PATH "%PATH%;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin"

      - name: Set up dependencies for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y build-essential yasm nasm libvpx-dev libx264-dev
          sudo apt install -y nvidia-cuda-toolkit

      - name: Set up dependencies for macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install yasm nasm

      - name: Install FFmpeg dependencies
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            choco install yasm
            choco install nasm
          fi

      - name: Compile FFmpeg with CUDA support
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            call "%VS140COMNTOOLS%..\..\..\VC\vcvarsall.bat" amd64
            git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
            cd ffmpeg
            git checkout release/7.1
            ./configure --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-gpl
            make -j$(nproc)
            make install
          fi
          
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
            cd ffmpeg
            git checkout release/7.1
            ./configure --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-gpl
            make -j$(nproc)
            sudo make install
          fi
          
          if [ ${{ matrix.os }} == 'macos-latest' ]; then
            git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
            cd ffmpeg
            git checkout release/7.1
            ./configure --enable-cuda --enable-cuvid --enable-nvenc --enable-nonfree --enable-gpl
            make -j$(nproc)
            sudo make install
          fi
