name: Build FFmpeg with CUDA and NVENC

on:
  workflow_dispatch:

jobs:
  build_ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            nasm yasm cmake autoconf automake libtool make pkg-config g++ \
            libmfx1 libmfx-tools intel-media-va-driver-non-free libmfx-dev \
            nvidia-cuda-toolkit nvidia-driver build-essential git

      - name: Clone and Build ffnvcodec (nv-codec-headers)
        run: |
          git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git
          cd nv-codec-headers
          make
          sudo make install

      - name: Clone and Build FFmpeg 7.1 with CUDA and NVENC
        run: |
          git clone --branch n7.1 --depth 1 https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          ./configure --enable-shared --disable-static --disable-autodetect \
            --enable-cuda --enable-nvenc --enable-cuvid --enable-vaapi \
            --enable-libmfx --enable-vulkan --prefix=$GITHUB_WORKSPACE/deps
          make -j$(nproc)
          make install

      - name: Upload FFmpeg
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-cuda-linux
          path: deps/
