name: Build Dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up vcpkg
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          bootstrap-vcpkg.bat
          vcpkg.exe update
          vcpkg.exe upgrade --no-dry-run

      - name: Install FFmpeg and PortAudio
        shell: cmd
        run: |
          vcpkg\vcpkg.exe install ffmpeg[nvcodec,qsv]:x64-windows-rel
          vcpkg\vcpkg.exe install portaudio:x64-windows
          echo BIN_FOLDER=%GITHUB_WORKSPACE%\vcpkg\installed\x64-windows\bin >> %GITHUB_ENV%
          echo INCLUDE_FOLDER=%GITHUB_WORKSPACE%\vcpkg\installed\x64-windows\include >> %GITHUB_ENV%

      - name: Configure CMake
        shell: bash
        run: |
          cmake -B build -S core/src/main/cpp \
            -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -DBIN_FOLDER=$BIN_FOLDER

      - name: Build Klarity
        shell: bash
        run: cmake --build build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-windows
          path: |
            build/bin/avcodec
            build/bin/avformat
            build/bin/avutil
            build/bin/swresample
            build/bin/swscale
            build/bin/klarity
            $INCLUDE_FOLDER/ffmpeg
            $INCLUDE_FOLDER/portaudio
