name: Build Windows Dependencies

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  build_windows_dependencies:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Chocolatey Dependencies
        run: |
          choco install nasm yasm cmake pkgconfiglite

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            git
            autoconf
            automake
            libtool
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-libiconv
            mingw-w64-x86_64-xz
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-rsync

      - name: Clone FFmpeg
        run: git clone --branch n7.1 --depth 1 https://github.com/FFmpeg/FFmpeg.git

      - name: Build FFmpeg 7.1
        shell: msys2 {0}
        run: |
          cd FFmpeg
          ./configure --enable-shared --disable-static --prefix=$GITHUB_WORKSPACE/deps
          make -j$(nproc)
          make install

      - name: Clone PortAudio
        run: git clone --branch v19.7.0 --depth 1 https://github.com/PortAudio/portaudio.git

      - name: Build PortAudio v19.7.0
        shell: msys2 {0}
        run: |
          cd portaudio
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/deps
          cmake --build build --config Release --target install

      - name: Organize Required Files
        shell: msys2 {0}
        run: |
          mkdir -p $GITHUB_WORKSPACE/deps/bin
          mkdir -p $GITHUB_WORKSPACE/deps/include

          rsync -av --ignore-existing $GITHUB_WORKSPACE/deps/include/ $GITHUB_WORKSPACE/deps/include/

          rsync -av --ignore-existing /mingw64/bin/av*.dll $GITHUB_WORKSPACE/deps/bin/
          rsync -av --ignore-existing /mingw64/bin/sw*.dll $GITHUB_WORKSPACE/deps/bin/
          rsync -av --ignore-existing /mingw64/bin/libiconv-2.dll $GITHUB_WORKSPACE/deps/bin/
          rsync -av --ignore-existing /mingw64/bin/liblzma-5.dll $GITHUB_WORKSPACE/deps/bin/
          rsync -av --ignore-existing /mingw64/bin/zlib1.dll $GITHUB_WORKSPACE/deps/bin/
          rsync -av --ignore-existing /mingw64/bin/libwinpthread-1.dll $GITHUB_WORKSPACE/deps/bin/
          rsync -av --ignore-existing /mingw64/bin/libgcc_s_seh-1.dll $GITHUB_WORKSPACE/deps/bin/
          rsync -av --ignore-existing /mingw64/bin/libstdc++-6.dll $GITHUB_WORKSPACE/deps/bin/

      - name: Upload FFmpeg & PortAudio
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-portaudio-windows
          path: deps/
