name: Build Dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up VCPKG
        id: vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV

      - name: Install PortAudio
        run: |
          $VCPKG_ROOT/vcpkg install portaudio --triplet ${{ matrix.triplet }}

      - name: Set up CMake
        uses: actions/setup-cmake@v4

      - name: Configure and Build klarity
        env:
          BIN_FOLDER: ${{ github.workspace }}/bin/${{ matrix.os }}
          LIB_FOLDER: ${{ github.workspace }}/lib/${{ matrix.os }}
        run: |
          mkdir -p $BIN_FOLDER $LIB_FOLDER
          cmake -B build -S core/src/main/cpp \
            -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} \
            -DBIN_FOLDER=$BIN_FOLDER \
            -DLIB_FOLDER=$LIB_FOLDER
          cmake --build build --config Release

      - name: Collect artifacts
        run: |
          mkdir -p artifacts/${{ matrix.os }}/bin
          mkdir -p artifacts/${{ matrix.os }}/lib
          mkdir -p artifacts/${{ matrix.os }}/include
          cp $BIN_FOLDER/* artifacts/${{ matrix.os }}/bin/
          cp $LIB_FOLDER/* artifacts/${{ matrix.os }}/lib/
          cp -r $VCPKG_ROOT/installed/${{ matrix.triplet }}/include/* artifacts/${{ matrix.os }}/include/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: artifacts/${{ matrix.os }}