name: Build libplacebo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: [ windows-latest ]
    #          - os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: haasn/libplacebo
          path: libplacebo

      - name: Set up dependencies
        run: |
          pip install meson ninja
          vcpkg install glfw3
          vcpkg install opengl

      - name: Configure and build
        shell: bash
        run: |
          meson setup build \
          --buildtype=release \
          --default-library=static \
          -Dd3d11=disabled \
          -Ddemos=false \
          -Dglslang=disabled \
          -Dlcms=disabled \
          -Dopengl=enabled \
          -Dshaderc=disabled \
          -Dunwind=disabled \
          -Dvulkan=disabled
          
          meson compile -C build

      - name: Package artifacts
        shell: bash
        working-directory: ./libplacebo/build
        run: |
          mkdir -p /tmp/libplacebo-artifacts
          find . -name '*.a' -o -name '*.lib' -exec cp {} /tmp/libplacebo-artifacts \;
          cp -r ../src/include /tmp/libplacebo-artifacts/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libplacebo-windows
          path: /tmp/libplacebo-artifacts/*