name: Build dependencies

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            triplet: x64-windows
            binary_ext: dll

          - os: macos-latest-arm64
            triplet: arm64-osx
            binary_ext: dylib

          - os: macos-latest
            triplet: x64-osx
            binary_ext: dylib

          - os: ubuntu-latest-arm64
            triplet: arm64-linux
            binary_ext: so

          - os: ubuntu-latest
            triplet: x64-linux
            binary_ext: so

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up nasm
        uses: ilammy/setup-nasm@v1

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          doNotCache: 'false'
          vcpkgJsonGlob: '**/core/src/main/cpp/vcpkg.json'
          runVcpkgInstall: 'true'

      - name: Upload installed
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            ${{ github.workspace }}/core/src/main/cpp/vcpkg_installed/${{ matrix.triplet }}