name: Build dependencies

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: windows-latest
            triplet: x64-windows
            artifact_name: klarity-deps-windows-x64
          - platform: ubuntu-latest
            triplet: x64-linux
            artifact_name: klarity-deps-linux-x64
          - platform: macos-latest
            triplet: x64-osx
            artifact_name: klarity-deps-macos-x64
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm

      - name: Bootstrap vcpkg (Unix)
        if: runner.os != 'Windows'
        run: ./bootstrap-vcpkg.sh
        working-directory: vcpkg

      - name: Bootstrap vcpkg (Windows)
        if: runner.os == 'Windows'
        run: .\bootstrap-vcpkg.bat
        working-directory: vcpkg

      - name: Install dependencies via manifest (Windows)
        if: runner.os == 'Windows'
        run: cmd.exe /C vcpkg\vcpkg install --triplet=${{ matrix.triplet }} --x-manifest-root=core/src/main/cpp --feature-flags=versions,manifest

      - name: Install dependencies via manifest (Linux/macOS)
        if: runner.os != 'Windows'
        run: ./vcpkg/vcpkg install --triplet=${{ matrix.triplet }} --x-manifest-root=core/src/main/cpp --feature-flags=versions,manifest

      - name: Prepare artifacts (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir artifacts
          mkdir artifacts/include
          mkdir artifacts/lib
          mkdir artifacts/bin

          copy vcpkg\installed\${{ matrix.triplet }}\include\* artifacts\include\ /Y
          copy vcpkg\installed\${{ matrix.triplet }}\lib\*.lib artifacts\lib\ /Y
          copy vcpkg\installed\${{ matrix.triplet }}\bin\*.dll artifacts\bin\ /Y
        shell: cmd

      - name: Prepare artifacts (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p artifacts/include artifacts/lib artifacts/bin

          cp -r vcpkg/installed/${{ matrix.triplet }}/include/* artifacts/include/ || true
          cp vcpkg/installed/${{ matrix.triplet }}/lib/*.so* artifacts/lib/ || true
          cp vcpkg/installed/${{ matrix.triplet }}/lib/*.dylib* artifacts/lib/ || true
          cp vcpkg/installed/${{ matrix.triplet }}/bin/* artifacts/bin/ || true

      - name: Compress artifacts
        run: tar -czf ${{ matrix.artifact_name }}.tar.gz -C artifacts .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.tar.gz
