name: Build dependencies

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            binary_ext: .so

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up nasm
        uses: ilammy/setup-nasm@v1.5.2

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/core/src/main/cpp/vcpkg.json'
          runVcpkgInstall: 'true'

        #      - name: Set up CMake
        #        uses: lukka/get-cmake@latest

      - name: Copy
        run: |
          ls -R ${{ github.workspace }}/installed
          ls -R _
          ls -R "${{ github.workspace }}/core/src/main/cpp"
          
          mkdir -p artifacts/${{ matrix.triplet }}
          if [ -d "${{ github.workspace }}/installed/${{ env.VCPKG_DEFAULT_TRIPLET }}" ]; then
            cp -r ${{ github.workspace }}/installed/${{ env.VCPKG_DEFAULT_TRIPLET }}/* artifacts/${{ matrix.triplet }}
          else
            echo "vcpkg installed directory does not exist"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: artifacts/${{ matrix.triplet }}